spring.datasource.url=jdbc:mysql://localhost:3306/agri_db
spring.datasource.username=root
spring.datasource.password=sash1411

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
